<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!-- DTD (Document Type Definition) interne, servant à définir l'architecture du document XML et la hiérarchie existant entre ses balises-->
<!DOCTYPE installation [
    <!ELEMENT installation (distribution*, PPA*, snap*)> <!-- Balise racine du corps du document XML -->

    <!ELEMENT distribution (categorie*)>            <!-- Balise racine de la structure concernant les paquets installés par le gestionnaire de paquets de la distribution Linux de l'utilisateur -->
    <!ELEMENT categorie (paquet*)>                  <!-- Définition de la balise "categorie", structurant la catégorie des paquets installés -->
    <!ATTLIST categorie cat CDATA #REQUIRED>        <!-- Définition de l'attribut "cat" de la balise "categorie". Cet attribut peut contenir n'importe quelle chaîne de caractères et est OBLIGATOIRE -->
    <!ELEMENT paquet (nom, description, script)>    <!-- Définition de la balise "paquets", structurant le nom, la version et la description du paquet souhaité-->
    <!ELEMENT nom (#PCDATA)>                        <!-- Définition de la balise "nom", contenant le nom des paquets -->
    <!ELEMENT description (#PCDATA)>                <!-- Définition de la balise "description", contenant la description des paquets installés -->
    <!ELEMENT script (#PCDATA)>                     <!-- Définition de la balise "script", contenant la version du script choisie (SIO ou personnalisée) -->
    <!ENTITY perso "personnel">
    <!ENTITY sio "SIO">

    <!ELEMENT PPA (categorie*)>                     <!-- Balise racine de la structure des paquets installés par les dépôts PPA -->

    <!ELEMENT snap (categorie*)>                    <!-- Balise racine de la structure des paquets installés par les dépôts PPA -->
]>

<!-- Balise racine du corps du document XML -->
<installation>
    <distribution>
        <categorie cat="Commandes de téléchargement">
            <paquet>
                <nom>curl</nom>
                <description>
                    ▪ Cette commande, à l’instar de Wget, permet de télécharger des fichiers téléchargeables depuis un site web.

                    ▪ Les similitudes et les différences entre ces deux commandes sont listées dans cet article → https://daniel.haxx.se/docs/curl-vs-wget.html

                    ▪ ATTENTION !!! COMME TOUT TÉLÉCHARGEMENT, NE TÉLÉCHARGEZ QUE DEPUIS UN SITE OFFICIEL, CONNU ET FIABLE !!!
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>python-pip</nom>
                <description>
                    ▪ Pip est un gestionnaire de paquets utilisé pour installer et gérer des paquets écrits en Python, tels des librairies Python (Flask ou encore Django pour du web).
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>snapd</nom>
                <description>
                    ▪ Cette commande permet l’installation de paquets Snap.

                    ▪ Snap est, à l’instar d’APT (Debian) ou de RPM (Fedora),un gestionnaire de paquets multi-distributions développé par Canonical, l’entreprise derrière le projet Ubuntu.

                    ▪ En plus de vous permettre d’installer de nombreux paquets déjà disponibles dans les dépôts officiels de votre distribution, Snap vous permet d’installer des paquets ne figurant pas dans ces mêmes dépôts, tels que Discord, Atom, Visual Studio Code, etc...
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>wget</nom>
                <description>
                    ▪ Cette commande vous permet de télécharger des fichiers téléchargeables disponibles sur une page web, en passant en arguments le ou les liens des fichiers que vous souhaitez télécharger.

                    ▪ ATTENTION !!! COMME TOUT TÉLÉCHARGEMENT, NE TÉLÉCHARGEZ QUE DEPUIS UN SITE OFFICIEL, CONNU ET FIABLE !!!
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>

        <categorie cat="3D">
            <paquet>
                <nom>blender</nom>
                <description>
                    ▪ Blender 3D est un excellent logiciel de modélisation 3D et d’animation, vous permettant d’exporter vos créations sous plusieurs formats de fichiers et sous de nombreuses options.

                    ▪ En outre, de nombreuses extensions sont disponibles.
                </description>
                <script>&perso;</script>
            </paquet>
        </categorie>

        <categorie cat="Commandes">
            <paquet>
                <nom>neofetch</nom>
                <description>
                    ▪ Cette commande permet d’afficher des informations concernant votre système d’exploitation, sur votre terminal,
                    à côté du logo de votre distribution, parfois dessiné en art ASCII.

                    ▪ Selon son fichier de configuration, la commande retourne (exemple sur ma distribution Kubuntu 18.04) :
                        • La version de votre système d’exploitation
                        • Le nom de l’hôte du système d’exploitation (votre ordinateur)
                        • La version de votre kernel (noyau Linux)
                        • Le temps écoulé depuis la connexion à votre session
                        • Le nombre de paquets installés
                        • L’interpréteur shell actuellement utilisé, ainsi que sa version
                        • La résolution de votre écran
                        • Votre environnement de bureau
                        • Votre gestionnaire de fenêtres
                        • Les thèmes de votre environnement de bureau
                        • Les thèmes d’icônes utilisés
                        • Le terminal actuellement utilisé
                        • Les caractéristiques principales de votre processeur
                        • Les caractéristiques principales de votre carte graphique
                        • La mémoire vive actuellement utilisée comparée à la mémoire vive totale
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>tree</nom>
                <description>
                    ▪ Cette commande est très pratique, elle vous permet de visualiser dans une arborescence tous les fichiers contenus dans les sous-dossiers à partir du dossier dans lequel vous lancez cette commande.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>sl</nom>
                <description>
                    ▪ Cette commande n’a rien de bien sérieux, si ce n’est d’afficher une locomotive à vapeur passer sur votre terminal si, au lieu de taper la commande « ls », vous tapez « sl » ou « LS ».
                </description>
                <script>&perso;</script>
            </paquet>
        </categorie>

        <categorie cat="Développement">
            <paquet>
                <nom>emacs</nom>
                <description>
                    ▪ Emacs est un éditeur de texte avancé se manipulant de la même manière que Nano, avec le clavier et les raccourcis claviers (à la différence près que l’on peut déplacer le curseur en cliquant sur la zone que l’on veut éditer).
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>g++</nom>
                <description>
                    ▪ Compilateur pour le langage C++.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>gcc</nom>
                <description>
                    ▪ Compilateur pour le langage C.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>git</nom>
                <description>
                    ▪ Git est un logiciel de gestion de versions décentralisé, généralement utilisé pour sauvegarder des versions d’un projet en programmation.

                    ▪ La documentation de Git se trouve sur ce site → https://git-scm.com/doc.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>make</nom>
                <description>
                    ▪ Make est une commande permettant de compiler tous les fichiers d’un projet listés dans un fichier de type Makefile avec les options souhaitées.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>umlet</nom>
                <description>
                    ▪ UMLet est un logiciel de dessin de diagrammes UML gratuit, libre et open-source.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>valgrind</nom>
                <description>
                    ▪ Valgrind est le meilleur ami des programmeurs C et C++ au moment où des erreurs de segmentation apparaissent au lancement d’un programme.

                    ▪ Cet utilitaire permet de débusquer des fuites mémoire, des mauvais pointeurs, et bien plus (voir la documentation de Valgrind pour plus d’informations).
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>

        <categorie cat="Disque">
            <paquet>
                <nom>k4dirstat</nom>
                <description>
                    ▪ K4dirstat est un excellent logiciel de nettoyage de disque manuel. Il est gratuit, libre et open-source.

                    ▪ Ce logiciel vous permettant de scanner un dossier choisi et de cartographier tous les fichiers du dossier et des sous-dossiers en carrés et rectangles. Plus ces carrés ou rectangles sont gros, plus ces fichiers sont volumineux.

                    ▪ Un point fort de ce logiciel par rapport à son équivalent Windows « Windirstat » est qu’il vous permet de partir à partir de n’importe quel dossier, si vous ne voulez pas partir depuis le dossier racine (ce qui évite de perdre du temps à scanner des dossiers non voulus dans les dossiers système pouvant peser jusqu’à plusieurs gigaoctets).
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>

        <categorie cat="Images">
            <paquet>
                <nom>gimp</nom>
                <description>
                    ▪ GIMP est un puissant logiciel d’édition d’image, la meilleure alternative gratuite, libre et open-source à Photoshop.

                    ▪ En outre, ce logiciel propose une myriade d'extensions.
                </description>
                <script>&perso;</script>
            </paquet>
        </categorie>

        <categorie cat="Internet">
            <paquet>
                <nom>thunderbird</nom>
                <description>
                    ▪ Thunderbird est un client messagerie développé par la fondation Mozilla. Sécurisé, gratuit, libre et open-source, vous proposant :
                        • La gestion de plusieurs comptes de messagerie, avec :
                            ◦ Recherche rapide de messages
                            ◦ Filtrage de messages
                            ◦ Groupement de messages
                            ◦ etc ...
                        • Un filtre de spams
                        • L’envoi de pièces jointes volumineuses (contournement efficace des limites des messageries Gmail, Outlook, etc...)
                        • La permission d’avoir une adresse de messagerie personnalisée
                        • Une myriade d’extensions
                </description>
                <script>sio</script>
            </paquet>
        </categorie>

        <categorie cat="Jeux">
            <paquet>
                <nom>bsdgames</nom>
                <description>
                    ▪ Ce paquet rajoute un « Snake » en version terminal. Vous devez ramasser le plus d’argent possible sans vous faire dévorer par le serpent. Vous pouvez quitter à tout moment en passant sur la dièse ‘#’ et sauvegarder votre record.
                </description>
                <script>&perso;</script>
            </paquet>
            <paquet>
                <nom>pacman</nom>
                <description>
                    ▪ Le nom du paquet n’est il pas assez explicite ?
                </description>
                <script>&perso;</script>
            </paquet>
            <paquet>
                <nom>supertux2</nom>
                <description>
                    ▪ Vous aimez Super Mario Bros ? Vous avez toujours voulu :
                        • Jouer à un clone libre et open-source de ce jeu légendaire, tout en incarnant le légendaire manchot Tux, la mascotte du noyau Linux ?
                        • Jouer à un jeu régulièrement mis à jour proposant, en plus des nombreux niveau disponibles, un nombre incalculable de niveaux créés par la communauté ?

                    ▪ Alors foncez, ce jeu est fait pour vous !
                </description>
                <script>&perso;</script>
            </paquet>
            <paquet>
                <nom>supertuxkart</nom>
                <description>
                    ▪ Même principe que Super Tux, mais appliqué à Mario Kart.
                </description>
                <script>&perso;</script>
            </paquet>
            <paquet>
                <nom>wesnoth</nom>
                <description>
                    ▪ The Battle for Wesnoth est un jeu de stratégie au tour par tour en 2D dont l’histoire se déroule dans un univers d’heroic-fantasy. Il est gratuit, libre et open-source.

                    ▪ Pour en savoir plus sur ce jeu, cliquez sur ce lien → https://linuxfr.org/news/sortie-de-la-bataille-pour-wesnoth-1-12.
                </description>
                <script>&perso;</script>
            </paquet>
        </categorie>

        <categorie cat="LAMP">
            <paquet>
                <nom>apache2</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php</nom>
                <description>
                    ▪ Comme son nom l'indique, ce paquet installe les librairies PHP.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>libapache2-mod</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>mariadb-server</nom>
                <description>
                    ▪ Ce paquet installe un serveur MariaDB.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-mysql</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-curl</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-gd</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-intl</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-json</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-mbstring</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-xml</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>php-zip</nom>
                <description></description>
                <script>&sio;</script>
            </paquet>
        </categorie>

        <categorie cat="Librairies">
            <paquet>
                <nom>libcsfml-dev</nom>
                <description>
                    ▪ Portage officiel de la librairie graphique SFML en C.
                </description>
                <script>&perso;</script>
            </paquet>
            <paquet>
                <nom>libsfml-dev</nom>
                <description>
                    ▪ La SFML (Standard and Fast Multimedia Library) est une librairie graphique permettant de créer des jeux vidéo en 2D ou encore des programmes interactifs en utilisant l’API graphique OpenGL.
                </description>
                <script>&perso;</script>
            </paquet>

            <paquet>
                <nom>python3.7</nom>
                <description>
                    ▪ La version de Python la plus récente, livrée avec son interpréteur.
                </description>
                <script>sio</script>
            </paquet>
        </categorie>

        <categorie cat="Réseau">
            <paquet>
                <nom>wireshark</nom>
                <description></description>
                <script>sio</script>
            </paquet>
        </categorie>

        <categorie cat="Vidéos">
            <paquet>
                <nom>vlc</nom>
                <description>
                    ▪ VLC est le lecteur audio et vidéo libre le plus populaire au monde. Il permet la lecture de nombreux formats de fichiers audio et vidéo.
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>

        <categorie cat="Wine">
            <paquet>
                <nom>wine-stable</nom>
                <description>
                    ▪ Wine (accronyme récursif de "Wine Is Not an Emulator") est un logiciel permettant l'exécution de certains programmes Windows sur Linux.
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>
    </distribution>

    <PPA>
        <categorie cat="">
            <paquet>
                <nom></nom>
                <description />
                <script></script>
            </paquet>
        </categorie>
    </PPA>

    <snap>
        <categorie cat="Internet">
            <paquet>
                <nom>discord</nom>
                <description>
                    ▪ Ce paquet installe le client Linux du célèbre réseau social.
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>

        <categorie cat="Programmation">
            <paquet>
                <nom>atom --classic</nom>
                <description>
                    ▪ Atom est un éditeur de code avancé libre et open-source permettant l'installation de très nombreuses extensions.

                    ▪ C'est par ailleurs avec cet éditeur que j'ai effectué la plus grosse partie du travail sur ce script de réinstallation.

                    ▪ Atom est installé par défaut avec Visual Studio Code, pour vous faire tester deux éditeurs de code. Vous pouvez supprimer l'éditeur dont vous ne voulez pas avant ou après le téléchargement, et garder l'éditeur de votre choix.
                </description>
                <script>&sio;</script>
            </paquet>
            <paquet>
                <nom>code --classic</nom>
                <description>
                    ▪ Visual Studio Code est un éditeur de code avancé open-source développé par Microsoft.

                    ▪ Visual Studio Code est installé par défaut avec Atom, pour vous faire tester deux éditeurs de code. Vous pouvez supprimer l'éditeur dont vous ne voulez pas avant ou après le téléchargement, et garder l'éditeur de votre choix.
                </description>
                <script>&sio;</script>
            </paquet>
        </categorie>
    </snap>
</installation>
